# Generated by Django 5.2.13 on 2026-04-30 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_user_managers_user_is_guest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_guest",
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("duration_sec", models.IntegerField()),
                ("calibrated", models.BooleanField(default=False)),
                ("good_percent", models.FloatField(default=0)),
                ("poor_duration", models.IntegerField(default=0)),
                ("psi", models.FloatField(default=100)),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("DEGRADING", "Degrading"),
                            ("IMPROVING", "Improving"),
                        ],
                        default="STABLE",
                        max_length=20,
                    ),
                ),
                ("drift_axes", models.JSONField(default=list)),
                ("alert_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
